name: Docs Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_DOCS_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DOCS_PROJECT_ID }}
on:
  release:
    types: [published]
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        working-directory: ./docs
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        working-directory: ./docs
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        working-directory: ./docs
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        working-directory: ./docs
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
